title:            Close Encouters of an Intimate Kind
url:              http://backinhorn.github.io
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: 
timezone:         Europe/London
paginate: 10
links: 
  - name:         About
    url:          /about